import type { Metadata } from "next"
import { SITE_URL } from "@/lib/schema"
import { Breadcrumb } from "@/components/layout/breadcrumb"

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "FreeToolPark privacy policy. Learn how we handle your data, cookies, and third-party services.",
  alternates: {
    canonical: `${SITE_URL}/privacy`,
  },
}

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-8">
      <Breadcrumb
        items={[
          { label: "Home", href: "/" },
          { label: "Privacy Policy" },
        ]}
      />

      <h1 className="font-heading mb-6 text-3xl font-bold">Privacy Policy</h1>
      <p className="mb-8 text-sm text-muted-foreground">
        Last updated: April 9, 2026
      </p>

      <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6 text-muted-foreground">
        <section>
          <h2 className="font-heading mb-3 text-xl font-semibold text-foreground">
            Overview
          </h2>
          <p>
            FreeToolPark ("we", "us", "our") operates the website
            www.freetoolpark.com. This page explains what data we collect, how we
            use it, and your rights regarding that data. We are committed to
            protecting your privacy and being transparent about our practices.
          </p>
        </section>

        <section>
          <h2 className="font-heading mb-3 text-xl font-semibold text-foreground">
            Data We Do Not Collect
          </h2>
          <p>
            All tools on FreeToolPark run entirely in your browser using
            client-side JavaScript. We do not collect, store, transmit, or log
            any data you enter into our tools. This includes but is not limited
            to:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1">
            <li>Text you paste into formatters, converters, or counters</li>
            <li>Passwords generated by the password generator</li>
            <li>JSON, Base64, or any encoded/decoded data</li>
            <li>Financial information entered into calculators</li>
            <li>QR code content or any file uploads</li>
          </ul>
          <p className="mt-2">
            You can verify this by inspecting your browser's Network tab while
            using any tool. No outgoing requests are made with your tool input
            data.
          </p>
        </section>

        <section>
          <h2 className="font-heading mb-3 text-xl font-semibold text-foreground">
            Data We Do Collect
          </h2>
          <p>We collect limited, non-personal data through the following means:</p>

          <h3 className="mt-4 mb-2 text-lg font-medium text-foreground">
            Analytics
          </h3>
          <p>
            We may use privacy-friendly analytics services to understand how
            visitors use our site. This data is aggregated and does not identify
            individual users. It may include page views, referral sources,
            browser type, device type, and approximate geographic region.
          </p>

          <h3 className="mt-4 mb-2 text-lg font-medium text-foreground">
            Advertising
          </h3>
          <p>
            We display advertisements from third-party ad networks (such as
            Google AdSense, Adsterra, or Ezoic) to support the free operation of
            this site. These networks may use cookies and similar technologies to
            serve ads based on your browsing activity. You can opt out of
            personalized advertising through your browser settings or through
            industry opt-out pages such as:
          </p>
          <ul className="mt-2 list-inside list-disc space-y-1">
            <li>Google Ad Settings (adssettings.google.com)</li>
            <li>Network Advertising Initiative (optout.networkadvertising.org)</li>
            <li>Digital Advertising Alliance (optout.aboutads.info)</li>
          </ul>

          <h3 className="mt-4 mb-2 text-lg font-medium text-foreground">
            Cookies
          </h3>
          <p>
            FreeToolPark itself does not set cookies. However, third-party ad
            networks and analytics services may set cookies on your device. These
            cookies are governed by the respective third party's privacy policy.
            You can manage or block cookies through your browser settings.
          </p>
        </section>

        <section>
          <h2 className="font-heading mb-3 text-xl font-semibold text-foreground">
            Hosting and Infrastructure
          </h2>
          <p>
            This website is hosted on Vercel. Vercel may collect server logs
            including IP addresses, request timestamps, and user agent strings as
            part of their infrastructure. This data is subject to Vercel's
            privacy policy at vercel.com/legal/privacy-policy.
          </p>
        </section>

        <section>
          <h2 className="font-heading mb-3 text-xl font-semibold text-foreground">
            Children's Privacy
          </h2>
          <p>
            FreeToolPark does not knowingly collect personal information from
            children under 13. Our tools do not require any personal information
            to use. If you believe a child has provided personal data to us,
            please contact us and we will take steps to remove it.
          </p>
        </section>

        <section>
          <h2 className="font-heading mb-3 text-xl font-semibold text-foreground">
            Changes to This Policy
          </h2>
          <p>
            We may update this privacy policy from time to time. Changes will be
            posted on this page with an updated revision date. Your continued use
            of the site after changes constitutes acceptance of the updated
            policy.
          </p>
        </section>

        <section>
          <h2 className="font-heading mb-3 text-xl font-semibold text-foreground">
            Contact
          </h2>
          <p>
            If you have questions about this privacy policy, you can reach us
            through the contact information provided on our website.
          </p>
        </section>
      </div>
    </div>
  )
}
