const BRAND_NAME = "FreeToolPark"
const BRAND_URL = "https://www.freetoolpark.com"

/**
 * Add branding to text/code exports
 */
export function addTextBranding(
  content: string,
  format: "json" | "text" | "code",
  options: { includeBranding?: boolean } = {}
): string {
  if (options.includeBranding === false) return content

  switch (format) {
    case "json":
      return `${content}\n\n// Generated by ${BRAND_NAME} - ${BRAND_URL}`
    case "code":
      return `${content}\n\n/* Generated by ${BRAND_NAME} - ${BRAND_URL} */`
    case "text":
    default:
      return `${content}\n\n---\nGenerated by ${BRAND_NAME} - ${BRAND_URL}`
  }
}

/**
 * Add branding to image canvas exports (PNG, QR codes, etc.)
 */
export function addCanvasBranding(
  canvas: HTMLCanvasElement,
  options: {
    includeBranding?: boolean
    position?: "bottom" | "corner"
  } = {}
): HTMLCanvasElement {
  if (options.includeBranding === false) return canvas

  const ctx = canvas.getContext("2d")
  if (!ctx) return canvas

  const position = options.position || "bottom"
  const brandText = `${BRAND_NAME}.com`

  ctx.font = "10px Arial"
  ctx.fillStyle = "rgba(150, 150, 150, 0.8)"

  if (position === "bottom") {
    ctx.textAlign = "center"
    ctx.fillText(brandText, canvas.width / 2, canvas.height - 8)
  } else {
    ctx.textAlign = "right"
    ctx.fillText(brandText, canvas.width - 8, canvas.height - 8)
  }

  return canvas
}

/**
 * CSV/Spreadsheet branding (add as last row)
 */
export function addCsvBranding(
  csvContent: string,
  options: { includeBranding?: boolean } = {}
): string {
  if (options.includeBranding === false) return csvContent

  return `${csvContent}\n\n"Generated by ${BRAND_NAME}","${BRAND_URL}"`
}
